Repository duelcontrolunit/YGOProAnalyticsServer, pull requests merged in 2019-06, with the labels that each got.

#36 Ygo 37
  YGOProAnalyticsServer/AdminConfig.cs
  YGOProAnalyticsServer/Controllers/DecklistController.cs
  YGOProAnalyticsServer/DTOs/AutomapperProfiles/Converters/DecklistStatisticsToTotalNumberOfGames.cs
  YGOProAnalyticsServer/DTOs/AutomapperProfiles/Converters/DecklistStatisticsToTotalNumberOfWinsConverter.cs
  YGOProAnalyticsServer/DTOs/AutomapperProfiles/DecklistToDecklistWithoutAnyAdditionalDatProfile.cs
  YGOProAnalyticsServer/DTOs/DecklistBrowserQueryParametersDTO.cs
  YGOProAnalyticsServer/DTOs/DecklistWithNumberOfGamesAndWinsDTO.cs
  YGOProAnalyticsServer/Helpers/CacheKeys.cs
  YGOProAnalyticsServer/IAdminConfig.cs
  YGOProAnalyticsServer/Services/Converters/DecklistToDecklistDtoConverter.cs
  YGOProAnalyticsServer/Services/Converters/Interfaces/IDecklistToDecklistDtoConverter.cs
  YGOProAnalyticsServer/Services/Others/BanlistService.cs
  YGOProAnalyticsServer/Services/Others/DecklistService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IBanlistService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IDecklistService.cs
  YGOProAnalyticsServer/Services/Validators/DateValidator.cs
  YGOProAnalyticsServer/Services/Validators/DecklistBrowserQueryParametersDtoValidator.cs
  YGOProAnalyticsServer/Services/Validators/Interfces/IDateValidator.cs
  YGOProAnalyticsServer/Services/Validators/Interfces/IDecklistBrowserQueryParametersDtoValidator.cs
  YGOProAnalyticsServer/Startup.cs
  YGOProAnalyticsServer/YGOProAnalyticsServer.csproj
  YGOProAnalyticsServerTests/Controllers/DecklistControllerTests.cs
  YGOProAnalyticsServerTests/Database/YgoProAnalyticsDatabaseTests.cs
  YGOProAnalyticsServerTests/Dtos/Automapper/Converters/DecklistStatisticsToTotalNumberOfGamesTests.cs
  YGOProAnalyticsServerTests/Dtos/Automapper/Converters/DecklistStatisticsToTotalNumberOfWinsConverterTests.cs
  YGOProAnalyticsServerTests/Others/BanlistServiceTests.cs
  YGOProAnalyticsServerTests/Others/DecklistServiceTests.cs
  YGOProAnalyticsServerTests/Services/Analyzers/ArchetypeOfDecklistAnalyzerTests.cs
  YGOProAnalyticsServerTests/Services/Analyzers/DuelLogNameAnalyzerTests.cs
  YGOProAnalyticsServerTests/Services/Analyzers/ServerActivityAnalyzerTests.cs
  YGOProAnalyticsServerTests/Services/Converters/DecklistToDecklistDTOConverterTests.cs
  YGOProAnalyticsServerTests/Services/Converters/DuelLogConverterTests.cs
  YGOProAnalyticsServerTests/Services/Validators/DecklistBrowserQueryParametersDtoValidatorTests.cs
  YGOProAnalyticsServerTests/TestingHelpers/CardsAndDecksHelper.cs
Labels: enhancement

#38 Development
  YGOProAnalyticsServer/AdminConfig.cs
  YGOProAnalyticsServer/Controllers/DecklistController.cs
  YGOProAnalyticsServer/DTOs/AutomapperProfiles/Converters/DecklistStatisticsToTotalNumberOfGames.cs
  YGOProAnalyticsServer/DTOs/AutomapperProfiles/Converters/DecklistStatisticsToTotalNumberOfWinsConverter.cs
  YGOProAnalyticsServer/DTOs/AutomapperProfiles/DecklistToDecklistWithoutAnyAdditionalDatProfile.cs
  YGOProAnalyticsServer/DTOs/DecklistBrowserQueryParametersDTO.cs
  YGOProAnalyticsServer/DTOs/DecklistWithNumberOfGamesAndWinsDTO.cs
  YGOProAnalyticsServer/EventHandlers/YgoProAnalysisBasedOnDataFromYgoProServer.cs
  YGOProAnalyticsServer/EventHandlers/YgoProServerDataRetriever.cs
  YGOProAnalyticsServer/Helpers/CacheKeys.cs
  YGOProAnalyticsServer/IAdminConfig.cs
  YGOProAnalyticsServer/Services/Converters/DecklistToDecklistDtoConverter.cs
  YGOProAnalyticsServer/Services/Converters/Interfaces/IDecklistToDecklistDtoConverter.cs
  YGOProAnalyticsServer/Services/Others/BanlistService.cs
  YGOProAnalyticsServer/Services/Others/DecklistService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IBanlistService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IDecklistService.cs
  YGOProAnalyticsServer/Services/Validators/DateValidator.cs
  YGOProAnalyticsServer/Services/Validators/DecklistBrowserQueryParametersDtoValidator.cs
  YGOProAnalyticsServer/Services/Validators/Interfces/IDateValidator.cs
  YGOProAnalyticsServer/Services/Validators/Interfces/IDecklistBrowserQueryParametersDtoValidator.cs
  YGOProAnalyticsServer/Startup.cs
  YGOProAnalyticsServer/YGOProAnalyticsServer.csproj
  YGOProAnalyticsServerTests/Controllers/DecklistControllerTests.cs
  YGOProAnalyticsServerTests/Database/YgoProAnalyticsDatabaseTests.cs
  YGOProAnalyticsServerTests/Dtos/Automapper/Converters/DecklistStatisticsToTotalNumberOfGamesTests.cs
  YGOProAnalyticsServerTests/Dtos/Automapper/Converters/DecklistStatisticsToTotalNumberOfWinsConverterTests.cs
  YGOProAnalyticsServerTests/Others/BanlistServiceTests.cs
  YGOProAnalyticsServerTests/Others/DecklistServiceTests.cs
  YGOProAnalyticsServerTests/Services/Analyzers/ArchetypeOfDecklistAnalyzerTests.cs
  YGOProAnalyticsServerTests/Services/Analyzers/DuelLogNameAnalyzerTests.cs
  YGOProAnalyticsServerTests/Services/Analyzers/ServerActivityAnalyzerTests.cs
  YGOProAnalyticsServerTests/Services/Converters/DecklistToDecklistDTOConverterTests.cs
  YGOProAnalyticsServerTests/Services/Converters/DuelLogConverterTests.cs
  YGOProAnalyticsServerTests/Services/Validators/DecklistBrowserQueryParametersDtoValidatorTests.cs
  YGOProAnalyticsServerTests/TestingHelpers/CardsAndDecksHelper.cs
Labels: enhancement

#42 Ygo 51
  YGOProAnalyticsServer/DTOs/DecklistBrowserResultsDTO.cs
  YGOProAnalyticsServer/Services/Others/BanlistService.cs
  YGOProAnalyticsServerTests/Others/ArchetypeServiceTests.cs
  YGOProAnalyticsServerTests/Others/BanlistServiceTests.cs
Labels: enhancement

#45 Development
  YGOProAnalyticsServer/AdminConfig.cs
  YGOProAnalyticsServer/Controllers/ArchetypeController.cs
  YGOProAnalyticsServer/Controllers/BanlistController.cs
  YGOProAnalyticsServer/Controllers/DecklistController.cs
  YGOProAnalyticsServer/DTOs/ArchetypeIdAndNameDTO.cs
  YGOProAnalyticsServer/DTOs/BanlistIdAndNameDTO.cs
  YGOProAnalyticsServer/DTOs/DecklistBrowserResultsDTO.cs
  YGOProAnalyticsServer/Helpers/CacheKeys.cs
  YGOProAnalyticsServer/IAdminConfig.cs
  YGOProAnalyticsServer/Services/Analyzers/ArchetypeAndDecklistAnalyzer.cs
  YGOProAnalyticsServer/Services/Factories/DecksDtosFactory.cs
  YGOProAnalyticsServer/Services/Others/ArchetypeService.cs
  YGOProAnalyticsServer/Services/Others/BanlistService.cs
  YGOProAnalyticsServer/Services/Others/DecklistService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IArchetypeService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IBanlistService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IDecklistService.cs
  YGOProAnalyticsServer/Startup.cs
  YGOProAnalyticsServerTests/Controllers/DecklistControllerTests.cs
  YGOProAnalyticsServerTests/Others/ArchetypeServiceTests.cs
  YGOProAnalyticsServerTests/Others/BanlistServiceTests.cs
  YGOProAnalyticsServerTests/Services/Factories/DecksDtosFactoryTests.cs
Labels: enhancement

#46 Ygo 49
  YGOProAnalyticsServer/AdminConfig.cs
  YGOProAnalyticsServer/Controllers/DecklistController.cs
  YGOProAnalyticsServer/DTOs/DecklistBrowserQueryParametersDTO.cs
  YGOProAnalyticsServer/IAdminConfig.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/INumberOfResultsHelper.cs
  YGOProAnalyticsServer/Services/Others/NumberOfResultsHelper.cs
  YGOProAnalyticsServer/Services/Validators/DecklistBrowserQueryParametersDtoValidator.cs
  YGOProAnalyticsServer/Services/Validators/Interfces/IDecklistBrowserQueryParametersDtoValidator.cs
  YGOProAnalyticsServer/Startup.cs
  YGOProAnalyticsServerTests/Controllers/DecklistControllerTests.cs
  YGOProAnalyticsServerTests/Others/INumberOfResultsHelperTests.cs
  YGOProAnalyticsServerTests/Services/Validators/DecklistBrowserQueryParametersDtoValidatorTests.cs
Labels: enhancement

#47 Development
  YGOProAnalyticsServer/AdminConfig.cs
  YGOProAnalyticsServer/Controllers/DecklistController.cs
  YGOProAnalyticsServer/DTOs/DecklistBrowserQueryParametersDTO.cs
  YGOProAnalyticsServer/IAdminConfig.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/INumberOfResultsHelper.cs
  YGOProAnalyticsServer/Services/Others/NumberOfResultsHelper.cs
  YGOProAnalyticsServer/Services/Validators/DecklistBrowserQueryParametersDtoValidator.cs
  YGOProAnalyticsServer/Services/Validators/Interfces/IDecklistBrowserQueryParametersDtoValidator.cs
  YGOProAnalyticsServer/Startup.cs
  YGOProAnalyticsServerTests/Controllers/DecklistControllerTests.cs
  YGOProAnalyticsServerTests/Others/INumberOfResultsHelperTests.cs
  YGOProAnalyticsServerTests/Services/Validators/DecklistBrowserQueryParametersDtoValidatorTests.cs
Labels: enhancement

#52 Ygo 35
  YGOProAnalyticsServer/Controllers/BanlistController.cs
  YGOProAnalyticsServer/DTOs/BanlistBrowserQueryParams.cs
  YGOProAnalyticsServer/DTOs/BanlistBrowserResultsDTO.cs
  YGOProAnalyticsServer/DTOs/BanlistStatisticsDTO.cs
  YGOProAnalyticsServer/DTOs/BanlistWithHowManyWasUsed.cs
  YGOProAnalyticsServer/DTOs/BanlistWithStatisticsDTO.cs
  YGOProAnalyticsServer/DTOs/DeckDTO.cs
  YGOProAnalyticsServer/DbModels/Banlist.cs
  YGOProAnalyticsServer/Services/Converters/BanlistToBanlistDTOConverter.cs
  YGOProAnalyticsServer/Services/Converters/Interfaces/IBanlistToBanlistDTOConverter.cs
  YGOProAnalyticsServer/Services/Factories/DecksDtosFactory.cs
  YGOProAnalyticsServer/Services/Factories/Interfaces/IDecksDtosFactory.cs
  YGOProAnalyticsServer/Services/Others/BanlistService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IBanlistService.cs
  YGOProAnalyticsServer/Services/Validators/BanlistBrowserQueryParamsValidator.cs
  YGOProAnalyticsServer/Services/Validators/Interfces/IBanlistBrowserQueryParamsValidator.cs
  YGOProAnalyticsServer/Startup.cs
  YGOProAnalyticsServerTests/Services/Converters/BanlistToBanlistDTOConverterTests.cs
  YGOProAnalyticsServerTests/Services/Validators/BanlistBrowserQueryParamsValidatorTests.cs
Labels: enhancement

#53 Development
  .gitignore
  YGOProAnalyticsServer/AdminConfig.cs
  YGOProAnalyticsServer/Controllers/BanlistController.cs
  YGOProAnalyticsServer/DTOs/BanlistBrowserQueryParams.cs
  YGOProAnalyticsServer/DTOs/BanlistBrowserResultsDTO.cs
  YGOProAnalyticsServer/DTOs/BanlistStatisticsDTO.cs
  YGOProAnalyticsServer/DTOs/BanlistWithHowManyWasUsed.cs
  YGOProAnalyticsServer/DTOs/BanlistWithStatisticsDTO.cs
  YGOProAnalyticsServer/DTOs/DeckDTO.cs
  YGOProAnalyticsServer/DbModels/Banlist.cs
  YGOProAnalyticsServer/IAdminConfig.cs
  YGOProAnalyticsServer/Jobs/UpdatesJob.cs
  YGOProAnalyticsServer/Services/Converters/BanlistToBanlistDTOConverter.cs
  YGOProAnalyticsServer/Services/Converters/Interfaces/IBanlistToBanlistDTOConverter.cs
  YGOProAnalyticsServer/Services/Factories/DecksDtosFactory.cs
  YGOProAnalyticsServer/Services/Factories/Interfaces/IDecksDtosFactory.cs
  YGOProAnalyticsServer/Services/Others/BanlistService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IBanlistService.cs
  YGOProAnalyticsServer/Services/Validators/BanlistBrowserQueryParamsValidator.cs
  YGOProAnalyticsServer/Services/Validators/Interfces/IBanlistBrowserQueryParamsValidator.cs
  YGOProAnalyticsServer/Startup.cs
  YGOProAnalyticsServerTests/AdminConfigTests.cs
  YGOProAnalyticsServerTests/Services/Converters/BanlistToBanlistDTOConverterTests.cs
  YGOProAnalyticsServerTests/Services/Validators/BanlistBrowserQueryParamsValidatorTests.cs
Labels: enhancement

#57 Ygo 65
  YGOProAnalyticsServer/EventHandlers/YgoProServerActivityAnalysisHandler.cs
  YGOProAnalyticsServer/Services/Updaters/Interfaces/IServerActivityUpdater.cs
  YGOProAnalyticsServer/Services/Updaters/ServerActivityUpdater.cs
  YGOProAnalyticsServer/Startup.cs
  YGOProAnalyticsServerTests/Services/Updater/ServerActivityUpdaterTests.cs
Labels: enhancement

#56 added missing params
  YGOProAnalyticsServer/Controllers/BanlistController.cs
Labels: bugFix

#55 Ygo 33
  YGOProAnalyticsServer/Controllers/ArchetypeController.cs
  YGOProAnalyticsServer/DTOs/ArchetypeBrowserQueryParams.cs
  YGOProAnalyticsServer/DTOs/ArchetypeBrowserResultsDTO.cs
  YGOProAnalyticsServer/DTOs/ArchetypeWithHowManyWinsAndHowManyWasUsed.cs
  YGOProAnalyticsServer/Services/Converters/ArchetypeToDtoConverter.cs
  YGOProAnalyticsServer/Services/Converters/Interfaces/IArchetypeToDtoConverter.cs
  YGOProAnalyticsServer/Services/Others/ArchetypeService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IArchetypeService.cs
  YGOProAnalyticsServer/Services/Validators/ArchetypeBrowserQueryParamsValidator.cs
  YGOProAnalyticsServer/Services/Validators/Interfces/IArchetypeBrowserQueryParamsValidator.cs
  YGOProAnalyticsServer/Startup.cs
  YGOProAnalyticsServerTests/Services/Converters/ArchetypeToDtoConverterTests.cs
  YGOProAnalyticsServerTests/Services/Validators/ArchetypeBrowserQueryParamsValidatorTests.cs
Labels: enhancement

#62 Ygo 63
  YGOProAnalyticsServer/Controllers/ArchetypeController.cs
  YGOProAnalyticsServer/DTOs/ArchetypeBrowserQueryParams.cs
  YGOProAnalyticsServer/Services/Others/ArchetypeService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IArchetypeService.cs
Labels: enhancement

#61 Ygo 64 v2
  YGOProAnalyticsServer/Controllers/ArchetypeController.cs
  YGOProAnalyticsServer/DTOs/ArchetypeStatisticsDTO.cs
  YGOProAnalyticsServer/DTOs/ConcreteStatisticsDTO.cs
  YGOProAnalyticsServer/Services/Converters/ArchetypeToDtoConverter.cs
  YGOProAnalyticsServer/Services/Converters/Interfaces/IArchetypeToDtoConverter.cs
  YGOProAnalyticsServer/Services/Others/ArchetypeService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IArchetypeService.cs
  YGOProAnalyticsServerTests/Services/Converters/ArchetypeToDtoConverterTests.cs
Labels: enhancement

#63 Development
  YGOProAnalyticsServer/Controllers/ArchetypeController.cs
  YGOProAnalyticsServer/DTOs/ArchetypeBrowserQueryParams.cs
  YGOProAnalyticsServer/DTOs/ArchetypeStatisticsDTO.cs
  YGOProAnalyticsServer/DTOs/ConcreteStatisticsDTO.cs
  YGOProAnalyticsServer/DbModels/Decklist.cs
  YGOProAnalyticsServer/EventHandlers/YgoProAnalysisBasedOnDataFromYgoProServer.cs
  YGOProAnalyticsServer/Services/Converters/ArchetypeToDtoConverter.cs
  YGOProAnalyticsServer/Services/Converters/Interfaces/IArchetypeToDtoConverter.cs
  YGOProAnalyticsServer/Services/Converters/YDKToDecklistConverter.cs
  YGOProAnalyticsServer/Services/Others/ArchetypeService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IArchetypeService.cs
  YGOProAnalyticsServerTests/Services/Converters/ArchetypeToDtoConverterTests.cs
  YGOProAnalyticsServerTests/Services/Converters/YDKToDecklistConverterTests.cs
Labels: enhancement

#65 Ygo 67
  YGOProAnalyticsServer/Controllers/DecklistController.cs
  YGOProAnalyticsServer/DTOs/DecklistBrowserQueryParametersDTO.cs
  YGOProAnalyticsServer/Services/Others/DecklistService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IDecklistService.cs
Labels: enhancement

#67 Development
  YGOProAnalyticsServer/Controllers/DecklistController.cs
  YGOProAnalyticsServer/DTOs/DecklistBrowserQueryParametersDTO.cs
  YGOProAnalyticsServer/Services/Others/DecklistService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IDecklistService.cs
Labels: enhancement

#68 Development
  YGOProAnalyticsServer/Database/YgoProAnalyticsDatabase.cs
  YGOProAnalyticsServer/DbModels/Banlist.cs
  YGOProAnalyticsServer/DbModels/DbJoinModels/DecklistsBanlistsJoin.cs
  YGOProAnalyticsServer/DbModels/Decklist.cs
  YGOProAnalyticsServer/EventHandlers/YgoProAnalysisBasedOnDataFromYgoProServer.cs
  YGOProAnalyticsServer/EventHandlers/YgoProServerDataRetriever.cs
  YGOProAnalyticsServer/Events/CardsRelatedUpdatesCompleted.cs
  YGOProAnalyticsServer/Events/DataFromYgoProServerRetrieved.cs
  YGOProAnalyticsServer/Jobs/UpdatesJob.cs
  YGOProAnalyticsServer/Services/Others/DecklistService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IDecklistService.cs
  YGOProAnalyticsServer/Services/Updaters/BanlistDataToBanlistUpdater.cs
  YGOProAnalyticsServer/Services/Updaters/CardsDataToCardsAndArchetypesUpdater.cs
  YGOProAnalyticsServer/Services/Updaters/Interfaces/IBanlistDataToBanlistUpdater.cs
  YGOProAnalyticsServerTests/Services/Updater/BanlistDataToBanlistUpdaterTests.cs
Labels: enhancement

#70 Development
  YGOProAnalyticsServer/Services/Others/BanlistService.cs
  YGOProAnalyticsServer/Services/Others/DecklistService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IBanlistService.cs
  YGOProAnalyticsServer/Services/Others/Interfaces/IDecklistService.cs
  YGOProAnalyticsServerTests/Controllers/DecklistControllerTests.cs
  YGOProAnalyticsServerTests/Others/DecklistServiceTests.cs
Labels: enhancement

#71 Ygo 71
  YGOProAnalyticsServer/Migrations/20190625145603_initializeDatabase.Designer.cs
  YGOProAnalyticsServer/Migrations/20190625145603_initializeDatabase.cs
  YGOProAnalyticsServer/Migrations/YgoProAnalyticsDatabaseModelSnapshot.cs
Labels: enhancement

#72 Development
  YGOProAnalyticsServer/Migrations/20190625145603_initializeDatabase.Designer.cs
  YGOProAnalyticsServer/Migrations/20190625145603_initializeDatabase.cs
  YGOProAnalyticsServer/Migrations/YgoProAnalyticsDatabaseModelSnapshot.cs
Labels: enhancement

#73 YGO-60 Refactoring in Startup file
  YGOProAnalyticsServer/Startup.cs
Labels: Refactoring

#74 Development
  YGOProAnalyticsServer/Startup.cs
Labels: Refactoring

#76 Ygo 81
  YGOProAnalyticsServer/Properties/launchSettings.json
  YGOProAnalyticsServer/Services/Others/DecklistService.cs
  YGOProAnalyticsServer/Services/Others/ServerActivityStatisticsService.cs
  YGOProAnalyticsServer/Startup.cs
Labels: bugFix
